/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Project { 
    project_name: string;
    project_description: string;
    project_tech: string;
    project_status: string;
    project_startDate: string;
    project_deadlineDate: string;
    project_lead: string;
    project_manager: string;
    project_client: string;
    management_tool: string;
    management_url: string;
    repo_tool: string;
    repo_url: string;
    project_budget: number;
    project_milestone_release_date: string;
    project_priority: string;
    project_location: string;
    project_type: Array<any>;
    project_approval_status: string;
    created_at?: string;
    project_user_id: string | null;
}

