/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    user_first_name: string;
    user_last_name: string;
    user_email: string;
    user_password: string;
    user_age: number;
    user_city: string;
    user_country: string;
    user_gender: string;
    user_state: string;
}

